---
title: dt06_calculate_shelfwide_racmoD_values.qmd
abstract: |
  The purpose of this notebook is to create shelfwide daily RACMO variables.
  This notebook is a similar premise to dt02, but for daily data (so slower).
  
  The same 27 shelves are used (see dt00 for their definition), and only pixels
  that are at least 50% ice shelf (according to MEaSURES Version 2, Mouginot et
  al. 2017) are included.
  
  The daily RACMO data was shared by co-author Christiaan van Dalum; it is from 
  the same model run as the monthly dataset (doi.org/10.5281/zenodo.5512076), 
  but saved as daily means / sums.
  
  Format the startDate and endDate params as "Mth-dd" (e.g. "Dec-24").
  
  Different standard R functions can be used as func; for example, "mean" 
  returns the average of the pixel values for pixels on a shelf; "sd" would 
  return the standard deviation of the pixel values across the shelf.
  
  The following RACMO variables can be used:
    - snowmelt, albd, t2m, radi;
    - turb, latf, senf;
    - swsd, swsu, swsn; 
    - lwsd, lwsu, lwsn;
    - w10m, u10m, v10m;
    - smb, precip, sndiv, subl.
    
  !! The following variables can only be used if they've been derived in dt01:
    - turb, radi, w10m, albd, swsn, lwsn
  
params:
  racmoVar:  "snowmelt"
  startDate: "Oct-28"
  endDate:   "Mar-04"
  func:      "mean"
---

# Data Prep & Set-Up
```{r}
## Run set-up scripts ----------------------------------------------------------
source("R/su01_set_up.R")
```

## Read in raw RACMO and subset based on the param dates
```{r}
# Read in based on the dates
racmoD <- polarcm::read_racmoD(params$racmoVar) |> 
  polarcm::subset_racmoD_by_summer(summers = 1980:2018) |>
  terrapin::subset_by_monthDay(periods = c(params$startDate, params$endDate))
```

## Prealloate & quick check of the dates here 
```{r}
# Preallocate with dates; each shelf will get a new column for the values
shelfwide  <- terrapin::get_date_info(racmoD)
funVarName <- paste(params$func, params$racmoVar, sep = "_") # to subset output

print(shelfwide)
```

# Shelfwide values -------------------------------------------------------------
```{r}
# Loop through each shelf
start <- domR::start_timer(params$racmoVar)
for (ii in pToken$shelves) {
  iiShelf <- polarcm::get_shelf_outline(ii)
  shelfwide[[ii]] <- polarcm::calc_fun_in_space(x = racmoD,
                                                extent = iiShelf,
                                                minArea = 0.5,
                                                FUN = params$func) |>
    _[[funVarName]]                 # subset output & ignore the dates
  domR::cat_progress(which(pToken$shelves == ii), length(pToken$shelves))
}
domR::print_line(" ")
end <- domR::end_timer(start, params$racmoVar)
```

## Handle units & precision
```{r}
# Grab columns with our data in; handles
colIndex <- pToken$shelves # [pToken$shelves %in% colnames(shelfwide)]

# We round based on the variation in the dataset
prec <- shelfwide[ ,colIndex] |> unlist() |>
  sd() |> signif(3) |> 
  domR::count_decimal_places()

# Round
shelfwide[ , colIndex] <- shelfwide[ , colIndex] |> round(prec)

# Convert units
if (params$racmoVar %in% pToken$varMass) {
    # from kg m-2 s-1 to kg m-2 day-1
    shelfwide[, colIndex] <- shelfwide[, colIndex] * (60 * 60 * 24)
} else if (params$racmoVar %in% pToken$varTemperature) {
    # from Kelvin to Celsius
    shelfwide[, colIndex] <- shelfwide[, colIndex] - 273.15
}
```

# Save =========================================================================
## Metadata
```{r}
blurb <- paste("These values are daily shelfwide-values. Units for masses are",
               "the mean total mass in kg per sq. metre of the respective ice",
               "shelf for that day (i.e. the units are kg m-2 day-1). Energy",
               "fluxes are similarly the mean total energy in a day for each sq.",
               "metre (W m-2 day-1). Temperatures are in K, and winds m s-1.",
               "The shelf boundaries are from MEaSURES Version 2 (Mouginot et",
               "al., 2017), and only pixels which are at least 50% shelf are",
               "included. Data is from RACMO2.3p3 but the daily datasets have",
               "been especially shared by co-author Christiaan van Dalum. See",
               "his 2022 TC paper for an overview of the RACMO setup.")

# Convert to a list to store with metadata
toSave <- list()
toSave$info <- domR::get_metadata(format = "json",
                                  blurb  = blurb,
                                  "shelves" = pToken$shelves)
toSave[[funVarName]] <- shelfwide
```

## Save as a json list
```{r}
dirName  <- paste0("Data/shelfwide_", params$func, "/")
if (!dir.exists(dirName)) dir.create(dirName)

fileName <- paste0(dirName, "racmoD_shelfwide_", funVarName, "-dt06.json")

domR::save_list(toSave, filename = fileName)
domR::cat_list(toSave$info)
```
